command_timeout = 1000

[character]
success_symbol = '[\[I\]](bold green) [â¯](bold green)'
error_symbol = '[\[I\]](bold green) [â¯](bold red)'
vicmd_symbol = '[\[N\]](bold red) [â¯](bold green)'

[kubernetes]
disabled = false

[docker_context]
format = "| [$symbol$context]($style) "

[golang]
format = "| [$symbol($version )]($style) "
symbol = "go "

[python]
format = '| [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[rust]
format = "| [$symbol($version )]($style) "
symbol = "ğ—¥ "
