command_timeout = 1000

[aws]
symbol = "îŒ½  "

[character]
success_symbol = '[\[I\]](bold green) [â–¶](bold green)'
error_symbol = '[\[I\]](bold green) [â–¶](bold red)'
vicmd_symbol = '[\[N\]](bold red) [â–¶](bold green)'

[kubernetes]
disabled = false

[docker_context]
symbol = "ïŒˆ "
format = "| [$symbol$context]($style) "

[golang]
format = "| [$symbol($version )]($style) "
symbol = "î˜§ "

[python]
symbol = "î˜† "
format = '| [${symbol}](yellow)[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
python_binary = ["python3", "python2"]


[rust]
format = "| [$symbol($version )]($style) "
symbol = "ğ—¥ "

[package]
format = "| [$symbol$version]($style) "
symbol = "ï£– "

[vagrant]
format = "| [$symbol($version )]($style) "

[username]
format = "[$user]($style)"
style_user = "bold #5192df"

[hostname]
format = "[@$hostname]($style):"
style = "bold #5192df"

[cmd_duration]
disabled = true

[directory]
read_only = " ï ½"
truncate_to_repo = true

[terraform]
format = "| [$symbol$workspace]($style) "
disabled = true

[git_branch]
symbol = "ï˜ "

[memory_usage]
symbol = "ï¡š "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[ruby]
symbol = "îˆ¾ "

[java]
symbol = "î‰– "

[shlvl]
symbol = "ï„  "
