command_timeout = 1000
format = """
${custom.corner_top}\
$username\
$hostname\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$endline\
$line_break\
${custom.corner_bot}\
$lua\
$jobs\
$battery\
$status\
$shell\
$character\
"""

right_format = """$kubernetes"""

[aws]
symbol = "  "
format = 'on [$symbol($profile )(\($region\) )(\[$duration\])]($style)'
disabled = true


[character]
vimcmd_symbol = '[❯](bold green)'
vimcmd_visual_symbol = '[❯](bold purple)'
vimcmd_replace_one_symbol = '[❯](bold red)'
vimcmd_replace_symbol = '[❯](bold red)'
success_symbol = '[❯](bold blue)'
error_symbol = '[❯](bold red)'

[custom.corner_top]
symbol = "╭─ "
style = "bold white"
when = true

[custom.corner_bot]
symbol = "╰"
style = "bold white"
when = true

[cmd_duration]
disabled = true

[dart]
format = "| [$symbol($version )]($style)"
symbol = " "

[directory]
read_only = " "
truncate_to_repo = false
truncation_symbol = "…/"
repo_root_style = "bold underline"

[docker_context]
disabled = true
symbol = " "
format = "| [$symbol$context]($style) "
only_with_files = true

# [fill]
# symbol = " "

[git_branch]
symbol = " "

[golang]
format = "| [$symbol($version )]($style)"
symbol = " "

[hostname]
format = "[@$hostname]($style):"
style = "bold #5192df"

[java]
format = "| [${symbol}(${version} )]($style)"
symbol = " "
detect_extensions = ["java", "class", "jar", "cljs", "cljc"]
detect_files = [
  "pom.xml",
  "build.sbt",
  ".java-version",
  "deps.edn",
  "project.clj",
  "build.boot",
]

[kotlin]
format = "| [$symbol($version )]($style)"
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\) )]($style)'
symbol = "☸ "
# format = "[$symbol$context]($style)"
style = "blue bold"

[lua]
disabled = true

[memory_usage]
symbol = " "

[nodejs]
format = "| [$symbol($version )]($style)"

[perl]
symbol = " "

[php]
symbol = " "

[package]
format = "| [$symbol$version]($style) "
symbol = "󰏗 "

[python]
symbol = " "
format = '| [${symbol}](yellow)[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = ["python3", "python2"]

[ruby]
symbol = " "

[rust]
format = "| [$symbol($version )]($style) "
symbol = " "

[time]
disabled = false
time_format = "%H%M"

[terraform]
format = "| [$symbol$workspace]($style) "
disabled = true

[username]
format = "[$user]($style)"
style_user = "bold #5192df"

[vagrant]
format = "| [$symbol($version )]($style) "
