command_timeout = 1000

[aws]
symbol = "îŒ½  "
format = 'on [$symbol($profile )(\($region\) )(\[$duration\])]($style)'
disabled = true

[character]
success_symbol = '[\[I\]](bold green) [â–¶](bold green)'
error_symbol = '[\[I\]](bold green) [â–¶](bold red)'
vicmd_symbol = '[\[N\]](bold red) [â–¶](bold green)'

[cmd_duration]
disabled = true

[directory]
read_only = " ï ½"
truncate_to_repo = true

[docker_context]
disabled = true
symbol = "ïŒˆ "
format = "| [$symbol$context]($style) "

[git_branch]
symbol = "ï˜ "

[golang]
format = "| [$symbol($version )]($style)"
symbol = "î˜§ "

[hostname]
format = "[@$hostname]($style):"
style = "bold #5192df"

[java]
symbol = "î‰– "

[kubernetes]
disabled = false

[memory_usage]
symbol = "ï¡š "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[package]
format = "| [$symbol$version]($style) "
symbol = "ï£– "

[python]
symbol = "î˜† "
format = '| [${symbol}](yellow)[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = ["python3", "python2"]

[ruby]
symbol = "îˆ¾ "

[rust]
format = "| [$symbol($version )]($style) "
symbol = "ğ—¥ "

[shlvl]
symbol = "ï„  "

[terraform]
format = "| [$symbol$workspace]($style) "
disabled = true

[username]
format = "[$user]($style)"
style_user = "bold #5192df"

[vagrant]
format = "| [$symbol($version )]($style) "

